FROM fedora:latest



USER root

RUN dnf install -y git && \
    git clone -b studying-actions https://github.com/qishenli/pash.git && \
    ./pash/scripts/distro-deps.sh && \
    ./pash/scripts/setup-pash.sh && \
    ./pash/pa.sh ./pash/evaluation/intro/hello-world.sh


