DROP TABLE IF EXISTS posts;

CREATE TABLE logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    worker TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    returncode INTEGER NOT NULL DEFAULT 0,
    stderr TEXT NOT NULL,
    shellscript TEXT DEFAULT NULL
);