# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dspash.proto import data_stream_pb2 as dspash_dot_proto_dot_data__stream__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dspash/proto/data_stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class DiscoveryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutAddr = channel.unary_unary(
                '/Discovery/PutAddr',
                request_serializer=dspash_dot_proto_dot_data__stream__pb2.PutAddrMsg.SerializeToString,
                response_deserializer=dspash_dot_proto_dot_data__stream__pb2.Status.FromString,
                _registered_method=True)
        self.GetAddr = channel.unary_unary(
                '/Discovery/GetAddr',
                request_serializer=dspash_dot_proto_dot_data__stream__pb2.AddrReq.SerializeToString,
                response_deserializer=dspash_dot_proto_dot_data__stream__pb2.GetAddrReply.FromString,
                _registered_method=True)
        self.RemoveAddr = channel.unary_unary(
                '/Discovery/RemoveAddr',
                request_serializer=dspash_dot_proto_dot_data__stream__pb2.AddrReq.SerializeToString,
                response_deserializer=dspash_dot_proto_dot_data__stream__pb2.Status.FromString,
                _registered_method=True)
        self.readStream = channel.unary_stream(
                '/Discovery/readStream',
                request_serializer=dspash_dot_proto_dot_data__stream__pb2.AddrReq.SerializeToString,
                response_deserializer=dspash_dot_proto_dot_data__stream__pb2.Data.FromString,
                _registered_method=True)
        self.writeStream = channel.stream_unary(
                '/Discovery/writeStream',
                request_serializer=dspash_dot_proto_dot_data__stream__pb2.Data.SerializeToString,
                response_deserializer=dspash_dot_proto_dot_data__stream__pb2.Status.FromString,
                _registered_method=True)
        self.PutAddrOptimized = channel.unary_unary(
                '/Discovery/PutAddrOptimized',
                request_serializer=dspash_dot_proto_dot_data__stream__pb2.PutAddrMsg.SerializeToString,
                response_deserializer=dspash_dot_proto_dot_data__stream__pb2.Status.FromString,
                _registered_method=True)
        self.GetAddrOptimized = channel.unary_unary(
                '/Discovery/GetAddrOptimized',
                request_serializer=dspash_dot_proto_dot_data__stream__pb2.AddrReq.SerializeToString,
                response_deserializer=dspash_dot_proto_dot_data__stream__pb2.GetAddrReply.FromString,
                _registered_method=True)
        self.FindPersistedOptimized = channel.unary_unary(
                '/Discovery/FindPersistedOptimized',
                request_serializer=dspash_dot_proto_dot_data__stream__pb2.FPMessage.SerializeToString,
                response_deserializer=dspash_dot_proto_dot_data__stream__pb2.FPMessageReply.FromString,
                _registered_method=True)
        self.RemovePersistedOptimized = channel.unary_unary(
                '/Discovery/RemovePersistedOptimized',
                request_serializer=dspash_dot_proto_dot_data__stream__pb2.RPMessage.SerializeToString,
                response_deserializer=dspash_dot_proto_dot_data__stream__pb2.Status.FromString,
                _registered_method=True)


class DiscoveryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PutAddr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAddr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAddr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def writeStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutAddrOptimized(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAddrOptimized(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindPersistedOptimized(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemovePersistedOptimized(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutAddr': grpc.unary_unary_rpc_method_handler(
                    servicer.PutAddr,
                    request_deserializer=dspash_dot_proto_dot_data__stream__pb2.PutAddrMsg.FromString,
                    response_serializer=dspash_dot_proto_dot_data__stream__pb2.Status.SerializeToString,
            ),
            'GetAddr': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAddr,
                    request_deserializer=dspash_dot_proto_dot_data__stream__pb2.AddrReq.FromString,
                    response_serializer=dspash_dot_proto_dot_data__stream__pb2.GetAddrReply.SerializeToString,
            ),
            'RemoveAddr': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAddr,
                    request_deserializer=dspash_dot_proto_dot_data__stream__pb2.AddrReq.FromString,
                    response_serializer=dspash_dot_proto_dot_data__stream__pb2.Status.SerializeToString,
            ),
            'readStream': grpc.unary_stream_rpc_method_handler(
                    servicer.readStream,
                    request_deserializer=dspash_dot_proto_dot_data__stream__pb2.AddrReq.FromString,
                    response_serializer=dspash_dot_proto_dot_data__stream__pb2.Data.SerializeToString,
            ),
            'writeStream': grpc.stream_unary_rpc_method_handler(
                    servicer.writeStream,
                    request_deserializer=dspash_dot_proto_dot_data__stream__pb2.Data.FromString,
                    response_serializer=dspash_dot_proto_dot_data__stream__pb2.Status.SerializeToString,
            ),
            'PutAddrOptimized': grpc.unary_unary_rpc_method_handler(
                    servicer.PutAddrOptimized,
                    request_deserializer=dspash_dot_proto_dot_data__stream__pb2.PutAddrMsg.FromString,
                    response_serializer=dspash_dot_proto_dot_data__stream__pb2.Status.SerializeToString,
            ),
            'GetAddrOptimized': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAddrOptimized,
                    request_deserializer=dspash_dot_proto_dot_data__stream__pb2.AddrReq.FromString,
                    response_serializer=dspash_dot_proto_dot_data__stream__pb2.GetAddrReply.SerializeToString,
            ),
            'FindPersistedOptimized': grpc.unary_unary_rpc_method_handler(
                    servicer.FindPersistedOptimized,
                    request_deserializer=dspash_dot_proto_dot_data__stream__pb2.FPMessage.FromString,
                    response_serializer=dspash_dot_proto_dot_data__stream__pb2.FPMessageReply.SerializeToString,
            ),
            'RemovePersistedOptimized': grpc.unary_unary_rpc_method_handler(
                    servicer.RemovePersistedOptimized,
                    request_deserializer=dspash_dot_proto_dot_data__stream__pb2.RPMessage.FromString,
                    response_serializer=dspash_dot_proto_dot_data__stream__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Discovery', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Discovery(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PutAddr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Discovery/PutAddr',
            dspash_dot_proto_dot_data__stream__pb2.PutAddrMsg.SerializeToString,
            dspash_dot_proto_dot_data__stream__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAddr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Discovery/GetAddr',
            dspash_dot_proto_dot_data__stream__pb2.AddrReq.SerializeToString,
            dspash_dot_proto_dot_data__stream__pb2.GetAddrReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveAddr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Discovery/RemoveAddr',
            dspash_dot_proto_dot_data__stream__pb2.AddrReq.SerializeToString,
            dspash_dot_proto_dot_data__stream__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def readStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Discovery/readStream',
            dspash_dot_proto_dot_data__stream__pb2.AddrReq.SerializeToString,
            dspash_dot_proto_dot_data__stream__pb2.Data.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def writeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/Discovery/writeStream',
            dspash_dot_proto_dot_data__stream__pb2.Data.SerializeToString,
            dspash_dot_proto_dot_data__stream__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutAddrOptimized(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Discovery/PutAddrOptimized',
            dspash_dot_proto_dot_data__stream__pb2.PutAddrMsg.SerializeToString,
            dspash_dot_proto_dot_data__stream__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAddrOptimized(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Discovery/GetAddrOptimized',
            dspash_dot_proto_dot_data__stream__pb2.AddrReq.SerializeToString,
            dspash_dot_proto_dot_data__stream__pb2.GetAddrReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindPersistedOptimized(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Discovery/FindPersistedOptimized',
            dspash_dot_proto_dot_data__stream__pb2.FPMessage.SerializeToString,
            dspash_dot_proto_dot_data__stream__pb2.FPMessageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemovePersistedOptimized(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Discovery/RemovePersistedOptimized',
            dspash_dot_proto_dot_data__stream__pb2.RPMessage.SerializeToString,
            dspash_dot_proto_dot_data__stream__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
