on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  pash-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Performance Tests
        run: |
          curl -s http://ctrl.pash.ndr.md/branch=main,action=PERFORMANCE
